# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hype-trakker-server-dev

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: hype-trakker-server-dev # set this to your application's name
    AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: '16.x'
    SLOT_NAME: 'Production'

jobs:
    build:
        name: Build, Test, Archive
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build

            - name: Move app dependencies to dist/
              run: |
                  mv package.json dist/
                  mv src/db dist/

            - name: Store the contents of dist/ as an Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: node-app
                  path: dist

    deploy:
        name: Deploy to Azure
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: node-app

            - name: Install production version of application
              run: |
                  npm install
                  npx prisma generate --schema ./db/schema.prisma

            - name: 'Deploy to Azure Web App'
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  slot-name: ${{ env.SLOT_NAME }}
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7233A7B128754FF68DAAEBDBBEBAE1F7 }}
                  package: .
